#!/usr/bin/env bash
# Immich Storage Template Configuration Helper
# This script provides the exact template and instructions

set -e

echo "=================================================="
echo "Immich Storage Template Configuration"
echo "=================================================="
echo ""
echo "✅ Services verified running - no errors found!"
echo ""
echo "Storage template organizes how photos are stored in:"
echo "  /mnt/photos/library/"
echo ""
echo "=================================================="
echo "RECOMMENDED TEMPLATE (copy this):"
echo "=================================================="
echo ""
echo "{{y}}/{{MM}}/{{dd}}/{{filename}}"
echo ""
echo "This creates: 2025/12/06/IMG_1234.jpg"
echo ""
echo "=================================================="
echo "TO APPLY:"
echo "=================================================="
echo ""
echo "1. Open browser to: https://hwc.ocelot-wahoo.ts.net:2283"
echo ""
echo "2. Login as admin"
echo ""
echo "3. Click your profile icon (top right) → Administration"
echo ""
echo "4. Click 'Settings' in left sidebar"
echo ""
echo "5. Scroll down to 'Storage Template' section"
echo ""
echo "6. Paste this template:"
echo "   {{y}}/{{MM}}/{{dd}}/{{filename}}"
echo ""
echo "7. Click 'Save' button"
echo ""
echo "=================================================="
echo "ALTERNATIVE TEMPLATES:"
echo "=================================================="
echo ""
echo "Monthly only:"
echo "  {{y}}/{{MM}}/{{filename}}"
echo "  Example: 2025/12/IMG_1234.jpg"
echo ""
echo "With day and hour:"
echo "  {{y}}/{{MM}}/{{dd}}-{{hh}}/{{filename}}"
echo "  Example: 2025/12/06-14/IMG_1234.jpg"
echo ""
echo "With album support:"
echo "  {{y}}/{{MM}}/{{album}}/{{filename}}"
echo "  Example: 2025/12/Vacation/IMG_1234.jpg"
echo ""
echo "=================================================="
echo "NOTES:"
echo "=================================================="
echo ""
echo "- Template only affects NEW uploads"
echo "- Existing photos won't move automatically"
echo "- To reorganize existing: Use 'Storage Migration Jobs'"
echo "  in the same settings page"
echo ""
echo "=================================================="
echo "Press Enter to exit..."
read
