# Beets container configuration
{ lib, config, pkgs, ... }:
let
  cfg = config.hwc.services.containers.beets;
  cfgRoot = "/opt/downloads/beets";

  generateConfigScript = pkgs.writeShellScript "beets-generate-config" ''
    set -euo pipefail

    install -d -m755 ${cfgRoot}

    cat > ${cfgRoot}/config.yaml <<'EOF'
# Beets Configuration
# Generated by NixOS configuration

directory: /music
library: /config/beets-library.db

# Import settings
import:
    move: yes
    copy: no
    write: yes
    incremental: yes
    timid: no
    log: /config/beets-import.log

# Path formats - Clean structure without year in folder names
paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title

# Plugins
plugins: duplicates fetchart embedart scrub replaygain missing info chroma web

# Plugin configurations
duplicates:
    checksum: ffmpeg
    copy: ""
    move: ""

fetchart:
    auto: yes
    cautious: yes
    cover_names: cover folder

embedart:
    auto: yes
    maxwidth: 1000

scrub:
    auto: yes

replaygain:
    auto: no
    backend: ffmpeg

# UI settings
ui:
    color: yes

# MusicBrainz settings
musicbrainz:
    searchlimit: 10

# Matching preferences - Lowered thresholds for better auto-matching
match:
    strong_rec_thresh: 0.15
    medium_rec_thresh: 0.40
    rec_gap_thresh: 0.40
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0

# Automatically skip when obvious - lowered for auto-acceptance
autotagger:
    strong_rec_thresh: 0.10

# Web interface
web:
    host: 0.0.0.0
    port: 8337
EOF

    chown -R 1000:100 ${cfgRoot}
    chmod 644 ${cfgRoot}/config/config.yaml
  '';
in
{
  config = lib.mkIf cfg.enable {
    # Service dependencies
    systemd.services."podman-beets".after = [ "network-online.target" ];
    systemd.services."podman-beets".wants = [ "network-online.target" ];

    # Generate configuration before container starts
    systemd.services."podman-beets".preStart = "${generateConfigScript}";
  };
}
