# domains/home/apps/qutebrowser/index.nix
{ config, lib, pkgs, ... }:
let
  cfg = config.hwc.home.apps.qutebrowser;
  package = if cfg.package != null then cfg.package else pkgs.qutebrowser;

  colors   = (config.hwc.home.theme or {}).colors or {};
  monoFont = lib.attrByPath [ "hwc" "home" "theme" "fonts" "mono" ] "monospace" config;

  keybindings = import ./parts/keybindings.nix { };
  appearance  = import ./parts/appearance.nix { inherit lib colors monoFont; };

  configPy = ''
    # Generated by domains/home/apps/qutebrowser — do not edit in place.
    # config.py wins over autoconfig.yml; runtime :set changes are session-only.
    config.load_autoconfig(False)

    # ── Behavior ─────────────────────────────────────────────────────────
    c.editor.command = ['kitty', '-e', 'nvim', '{file}', '+{line}']
    c.content.blocking.method = 'both'          # hosts lists + Brave adblock lib
    c.content.autoplay = False
    c.scrolling.smooth = True
    c.tabs.show = 'multiple'
    c.tabs.position = 'top'
    c.completion.height = '40%'
    c.downloads.location.directory = '~/Downloads'
    c.downloads.remove_finished = 30000

    ${appearance}
    ${keybindings}
  '';
in
{
  #==========================================================================
  # OPTIONS
  #==========================================================================
  options.hwc.home.apps.qutebrowser = {
    enable = lib.mkEnableOption "Qutebrowser keyboard-focused browser";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = "Package to use for qutebrowser.";
    };

    extraPackages = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = [];
      description = "Additional packages to install alongside qutebrowser.";
    };
  };

  #==========================================================================
  # IMPLEMENTATION
  #==========================================================================
  config = lib.mkIf cfg.enable {
    home.packages = [ package ] ++ cfg.extraPackages;

    xdg.configFile."qutebrowser/config.py".text = configPy;

    #==========================================================================
    # VALIDATION
    #==========================================================================
    assertions = [
      {
        assertion = cfg.package != null || (pkgs ? qutebrowser);
        message = "Package qutebrowser not found in nixpkgs and no custom package provided";
      }
    ];
  };
}