# domains/system/users.nix
#
# User accounts, identity constants, and SSH configuration
#
# NAMESPACE: hwc.system.users.*, hwc.system.core.identity.*
# USAGE: hwc.system.users.enable = true;

{ config, lib, pkgs, ... }:

let
  usersCfg = config.hwc.system.users;
  idCfg = config.hwc.system.core.identity;
  userExists = config.users.users ? ${idCfg.user};
  actualUser = if userExists then config.users.users.${idCfg.user} else null;
in
{
  #==========================================================================
  # OPTIONS — Identity constants (PUID/PGID/user/group)
  #==========================================================================
  options.hwc.system.core.identity = {
    puid = lib.mkOption {
      type = lib.types.int;
      default = 1000;
      description = "Primary user ID for services and containers.";
    };

    pgid = lib.mkOption {
      type = lib.types.int;
      default = 100;
      description = "Primary group ID (users group = 100, NOT 1000).";
    };

    user = lib.mkOption {
      type = lib.types.str;
      default = "eric";
      description = "Primary username for services and containers.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "users";
      description = "Primary group name for services and containers.";
    };
  };

  #==========================================================================
  # OPTIONS — User accounts
  #==========================================================================
  options.hwc.system.users = {
    enable = lib.mkEnableOption "Enable HWC user management system";
    emergencyEnable = lib.mkEnableOption "Enable emergency root access during migration";

    user = {
      enable = lib.mkEnableOption "Eric user account configuration";

      name = lib.mkOption {
        type = lib.types.str;
        default = "eric";
        description = "Username for the primary user account";
      };

      description = lib.mkOption {
        type = lib.types.str;
        default = "Eric - Heartwood Craft";
        description = "Full name description for user account";
      };

      shell = lib.mkOption {
        type = lib.types.package;
        default = pkgs.zsh;
        description = "Default shell for user account";
      };

      useSecrets = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Use agenix secrets for user password management";
      };

      fallbackPassword = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = "il0wwlm?";
        description = "Fallback password if useSecrets is false.";
      };

      fallbackHashedPassword = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = "$6$McKMuWn2JliY4HR.$0pDd/FJPdbENIqCwXIMsXXEZcaLOriieUZlXEb0YxnqAUrJiZ05SIdVJVQ5BnR3TksU9DGoZcGBGzB5qiFT0b/";
        description = "Hashed fallback password.";
      };

      groups = {
        basic = lib.mkEnableOption "basic user groups (wheel, networkmanager)";
        media = lib.mkEnableOption "media access groups (video, audio)";
        development = lib.mkEnableOption "development groups (docker, podman)";
        virtualization = lib.mkEnableOption "virtualization groups (libvirtd, kvm)";
        hardware = lib.mkEnableOption "hardware access groups (input, uucp)";
      };

      ssh = {
        enable = lib.mkEnableOption "SSH configuration for user";

        useSecrets = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Use agenix secrets for SSH keys";
        };

        fallbackKey = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICubgcmg6aBisQC+MWRC4RWOY8zIHEl42O7bTbzyCiGB eriqueo@proton.me"
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII0vCGDNeuXjY1vDOLVCZLbCUOb1iI3IGIKTZazYKgCc Generated By Termius"
          ];
          description = "Fallback SSH public keys if secrets not available";
        };
      };

      environment = {
        enablePaths = lib.mkEnableOption "export HWC path environment variables";
        enableZsh = lib.mkEnableOption "ZSH system-level configuration";
      };
    };
  };

  #==========================================================================
  # IMPLEMENTATION
  #==========================================================================
  config = lib.mkMerge [
    # Identity validation (always active)
    {
      assertions = [
        {
          assertion = !userExists || actualUser.uid == null || actualUser.uid == idCfg.puid;
          message = ''
            hwc.system.core.identity.puid (${toString idCfg.puid}) does not match
            actual UID of user "${idCfg.user}" (${toString actualUser.uid}).
          '';
        }
        {
          assertion = idCfg.pgid == 100;
          message = ''
            hwc.system.core.identity.pgid must be 100 (the users group GID).
            Current value: ${toString idCfg.pgid}
          '';
        }
        {
          assertion = idCfg.group == "users";
          message = ''
            hwc.system.core.identity.group must be "users".
            Current value: ${idCfg.group}
          '';
        }
      ];
    }

    # User account (when enabled)
    (lib.mkIf (usersCfg.enable && usersCfg.user.enable) {
      users.mutableUsers = false;

      users.groups.secrets = {};

      users.users.${usersCfg.user.name} = {
        isNormalUser = true;
        home = "/home/${usersCfg.user.name}";
        group = "users";
        shell = usersCfg.user.shell;
        description = usersCfg.user.description;
        autoSubUidGidRange = true;

        extraGroups =
          (lib.optionals usersCfg.user.groups.basic          [ "wheel" "networkmanager" "bluetooth" "secrets" ]) ++
          (lib.optionals usersCfg.user.groups.media           [ "video" "audio" "render" ]) ++
          (lib.optionals usersCfg.user.groups.development     [ "docker" "podman" ]) ++
          (lib.optionals usersCfg.user.groups.virtualization  [ "libvirtd" "kvm" ]) ++
          (lib.optionals usersCfg.user.groups.hardware        [ "input" "uucp" ]);

        hashedPassword = lib.mkIf (
          (!usersCfg.user.useSecrets || !(config.hwc.secrets.api ? "user-initial-password"))
          && usersCfg.user.fallbackHashedPassword != null
        ) usersCfg.user.fallbackHashedPassword;

        hashedPasswordFile = lib.mkIf (usersCfg.user.useSecrets && config.hwc.secrets.api ? "user-initial-password")
          config.age.secrets.user-initial-password.path;

        openssh.authorizedKeys.keys = lib.mkIf usersCfg.user.ssh.enable (
          if usersCfg.user.ssh.useSecrets && config.hwc.secrets.api ? "user-ssh-public-key" then
            [ (builtins.readFile config.age.secrets.user-ssh-public-key.path) ]
          else
            usersCfg.user.ssh.fallbackKey
        );
      };

      programs.zsh.enable = true;

      assertions = [
        {
          assertion = !usersCfg.user.useSecrets || config.hwc.secrets.enable;
          message = "hwc.system.users.useSecrets requires hwc.secrets.enable = true";
        }
        {
          assertion = !usersCfg.user.ssh.useSecrets || config.hwc.secrets.enable;
          message = "hwc.system.users.ssh.useSecrets requires hwc.secrets.enable = true";
        }
        {
          assertion = usersCfg.user.fallbackPassword != null;
          message = "CRITICAL: No fallbackPassword set. Required for emergency access when agenix fails.";
        }
      ];

      warnings = lib.optionals (usersCfg.user.useSecrets && !(config.hwc.secrets.api ? "user-initial-password")) [
        ''
          AGENIX FALLBACK ACTIVE: user-initial-password not available.
          Using fallback password for emergency access.
        ''
      ] ++ lib.optionals (usersCfg.user.ssh.useSecrets && !(config.hwc.secrets.api ? "user-ssh-public-key")) [
        ''
          AGENIX FALLBACK ACTIVE: user-ssh-public-key not available.
          Using fallback SSH keys for emergency access.
        ''
      ];
    })
  ];
}
