#!/usr/bin/env bash
# domains/ai/framework/parts/grebuild-docs.sh
#
# Grebuild integration - Post-rebuild documentation with Charter awareness
# Replaces post-rebuild-ai-docs service with framework-based approach

set -euo pipefail

# Configuration
NIXOS_DIR="${NIXOS_DIR:-/home/eric/.nixos}"
OUTPUT_DIR="${OUTPUT_DIR:-${NIXOS_DIR}/docs/ai-doc}"
OLLAMA_ENDPOINT="${OLLAMA_ENDPOINT:-http://localhost:11434}"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info() { echo -e "${GREEN}✅${NC} $*"; }
log_warn() { echo -e "${YELLOW}⚠️${NC} $*"; }
log_error() { echo -e "${RED}❌${NC} $*" >&2; }
log_header() { echo -e "\n${BOLD}${BLUE}$*${NC}"; }

# Check if Ollama is running
check_ollama() {
  if ! systemctl is-active --quiet podman-ollama.service; then
    log_warn "Ollama service not active; skipping documentation generation"
    return 1
  fi

  if ! curl --fail --silent --show-error --max-time 5 "$OLLAMA_ENDPOINT/api/tags" >/dev/null 2>&1; then
    log_warn "Ollama not available at $OLLAMA_ENDPOINT, skipping documentation generation"
    return 1
  fi

  return 0
}

# Main documentation generation
main() {
  log_header "🤖 Post-Rebuild AI Documentation Generator (Framework-based)"

  # Check Ollama availability
  if ! check_ollama; then
    log_info "Skipping AI documentation (Ollama not available)"
    exit 0
  fi

  # Change to nixos directory
  cd "$NIXOS_DIR" || {
    log_error "Could not change to $NIXOS_DIR"
    exit 1
  }

  # Ensure output directory exists
  mkdir -p "$OUTPUT_DIR"
  chown eric:users "$OUTPUT_DIR" 2>/dev/null || true

  # Get recent changes
  log_info "Analyzing recent NixOS configuration changes..."

  RECENT_CHANGES=$(git log -5 --pretty=format:"%h - %s (%ar)" --no-merges 2>/dev/null || echo "No recent changes")
  CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null || echo "No files changed")
  LAST_COMMIT=$(git log -1 --pretty=format:"%h - %s" 2>/dev/null || echo "No commit info")

  # Get first changed file for Charter context (or use generic)
  FIRST_CHANGED_FILE=$(echo "$CHANGED_FILES" | head -n1)
  if [[ -z "$FIRST_CHANGED_FILE" ]]; then
    FIRST_CHANGED_FILE="domains/system"
  fi

  # Generate timestamp
  TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
  OUTPUT_FILE="$OUTPUT_DIR/rebuild-docs-$TIMESTAMP.md"

  log_info "Generating Charter-aware documentation using AI Framework..."

  # Use ollama-wrapper for documentation generation
  if ! command -v ollama-wrapper >/dev/null 2>&1; then
    log_error "ollama-wrapper not found (AI framework not installed?)"
    exit 1
  fi

  # Create temporary prompt file
  PROMPT_FILE=$(mktemp)
  cat > "$PROMPT_FILE" <<EOF
You are a NixOS expert documenting system rebuild changes. Generate comprehensive documentation for this rebuild.

Recent NixOS Configuration Changes:
$RECENT_CHANGES

Files Changed in Last Commit:
$CHANGED_FILES

Last Commit:
$LAST_COMMIT

Generate a markdown documentation report that includes:

## Summary
Brief overview of changes made (2-3 sentences)

## Configuration Changes
- Specific modules/options modified
- New features added or removed
- Charter compliance notes (cite specific Laws if relevant)

## Impact Analysis
- What systems/services are affected
- Potential side effects or dependencies
- Performance or resource impact

## Testing Recommendations
- What to test after this rebuild
- Expected behavior changes
- Validation steps

## Troubleshooting
- Common issues that might arise
- How to diagnose problems
- Rollback instructions if needed

## Next Steps
- Recommended follow-up actions
- Configuration to review
- Documentation to update

Keep it concise, actionable, and focused on what the user needs to know.
EOF

  # Execute with ollama-wrapper (uses framework's thermal safety)
  RESULT=$(ollama-wrapper doc medium "$FIRST_CHANGED_FILE" 2>&1) || {
    log_warn "Documentation generation failed"
    rm -f "$PROMPT_FILE"
    exit 0  # Non-fatal
  }

  rm -f "$PROMPT_FILE"

  # Write documentation file
  cat > "$OUTPUT_FILE" <<EOF
# NixOS Rebuild Documentation

**Generated:** $(date)
**Host:** $(hostname)
**User:** $(whoami)
**Profile:** ${PROFILE:-auto}

---

$RESULT

---

## System Information

- **Generated by:** AI Framework (grebuild integration)
- **Timestamp:** $TIMESTAMP
- **NixOS Config:** $NIXOS_DIR

## Recent Git History

\`\`\`
$RECENT_CHANGES
\`\`\`

## Changed Files

\`\`\`
$CHANGED_FILES
\`\`\`

## Charter Context

This documentation was generated with Charter v9.1 awareness.
Relevant architectural rules were considered during generation.

EOF

  chown eric:users "$OUTPUT_FILE" 2>/dev/null || true

  log_info "Documentation saved to: $OUTPUT_FILE"

  # Keep only last 10 documentation files
  cd "$OUTPUT_DIR"
  find . -name "rebuild-docs-*.md" -type f | \
    sort -r | \
    tail -n +11 | \
    xargs -r rm -f

  log_info "Post-rebuild documentation complete!"

  # Show preview (first 20 lines)
  echo ""
  echo "=== Documentation Preview ==="
  head -n 20 "$OUTPUT_FILE"
  echo "..."
  echo "=== (Full documentation in $OUTPUT_FILE) ==="
}

main "$@"
