# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  
  # Bootloader configuration (UEFI)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42d7ef27-5af7-4929-b0f4-f6247d4b1551";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/01C8-BA8F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Swap space for server (16GB) - prevents OOM kills during high load
  # Located on SSD for better performance
  swapDevices = [{
    device = "/var/swapfile";
    size = 16384; # 16GB in MB
  }];

  # Static IP for LAN reliability (works even if router DHCP fails)
  # This ensures Jellyfin is always reachable at 192.168.0.97 on local network
  networking.useDHCP = lib.mkDefault false;
  networking.interfaces.eno1 = {
    useDHCP = false;
    ipv4.addresses = [{
      address = "192.168.0.97";
      prefixLength = 24;
    }];
  };
  networking.defaultGateway = "192.168.0.1";
  networking.nameservers = [ "192.168.0.1" "1.1.1.1" "8.8.8.8" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
