#!/usr/bin/env bash
set -euo pipefail

# Generated by Nix; simple helpers
tag() { notmuch tag "$@"; }

# 0) Normalize special folders (server paths → tags)
# Proton
tag +sent    -inbox -unread -- 'path:"proton/Sent"'
tag +trash   -inbox -unread -- 'path:"proton/Trash"'
tag +spam    -inbox -unread -- 'path:"proton/Spam"'
tag +archive -inbox        -- 'path:"proton/Archive" OR path:"proton/All Mail"'
tag +draft   -inbox -unread -- 'path:"proton/Drafts"'

# Gmail (both namespace variants)
tag +sent    -inbox -unread -- 'path:"gmail-*/[Gmail]/Sent Mail" OR path:"gmail-*/[Google Mail]/Sent Mail"'
tag +trash   -inbox -unread -- 'path:"gmail-*/[Gmail]/Trash"     OR path:"gmail-*/[Google Mail]/Trash"'
tag +spam    -inbox -unread -- 'path:"gmail-*/[Gmail]/Spam"      OR path:"gmail-*/[Google Mail]/Spam"'
tag +archive -inbox        -- 'path:"gmail-*/[Gmail]/All Mail"   OR path:"gmail-*/[Google Mail]/All Mail"'
tag +draft   -inbox -unread -- 'path:"gmail-*/[Gmail]/Drafts"    OR path:"gmail-*/[Google Mail]/Drafts"'

# 1) Newsletters (List-Id header or common senders)
tag +newsletter -inbox -- 'list:"*"'
# Sender substrings rendered below by Nix:
__NEWSLETTER_BLOCK__

# 2) Notifications (bots, noreply, GitHub, etc.)
__NOTIFICATION_BLOCK__

# 3) Finance (receipts, statements)
__FINANCE_BLOCK__

# 4) Action-worthy subjects (quick heuristics)
__ACTION_SUBJECT_BLOCK__

# 5) Safety: don’t mark sent/trash/spam/draft as action/newsletter/notification/etc.
tag -action -newsletter -notification -- 'tag:sent OR tag:trash OR tag:spam OR tag:draft'

# Optional: stale-action helper (add +stale for >7d action)
# notmuch tag +stale -- 'tag:action AND date:..7days ago'
