{ lib, pkgs, config, ... }:
let
  accVals = lib.attrValues (config.hwc.home.mail.accounts or {});
  imap0 = lib.lists.imap0;

  # leader-based quick folder nav per account (optional, simple example)
  accountBindings =
    lib.concatStringsSep "\n"
      (imap0 (i: acc:
        let n = toString (i + 1);
            md = acc.maildirName or acc.name or "INBOX";
        in " # ,g${n}: :cf ${md}<Enter>"
      ) accVals);
in
{
  files = profileBase: {
    ".config/aerc/binds.conf".text = ''
      # =============================================
      # Universal Keybinding System - Aerc
      # Generated by Nix
      # =============================================

      # Global keybindings (no section header in aerc 0.21.0+)
      <C-h> = :prev-tab<Enter>
      <C-l> = :next-tab<Enter>
      <C-q> = :prompt 'Quit aerc?' quit<Enter>
      <C-t> = :term<Enter>
      ?     = :help keys<Enter>
      <C-r> = :exec mbsync -a<Enter>

      [messages]
      j = :next<Enter>
      k = :prev<Enter>
      h = :prev-folder<Enter>
      l = :next-folder<Enter>
      g = :select 0<Enter>
      G = :select -1<Enter>
      <C-d> = :next 50%<Enter>
      <C-u> = :prev 50%<Enter>
      <Enter> = :view<Enter>
      q = :quit<Enter>

      J = :mark -t<Enter>:next<Enter>
      K = :mark -t<Enter>:prev<Enter>
      V = :mark -v<Enter>

      d = :archive flat<Enter>
      D = :delete<Enter>
      c = :compose<Enter>
      C = :reply -aq<Enter>

      X = :mv<space>
      Y = :cp<space>

      [view]
      q = :close<Enter>
      j = :next<Enter>
      k = :prev<Enter>
      d = :archive flat<Enter>:close<Enter>
      D = :delete<Enter>:close<Enter>
      c = :compose<Enter>
      C = :reply -aq<Enter>
      H = :toggle-headers<Enter>
      / = :toggle-key-passthrough<Enter>/

      [view::passthrough]
      $noinherit = true
      <Esc> = :toggle-key-passthrough<Enter>

      ${accountBindings}
    '';
  };
}
