# modules/home/apps/aerc/parts/config.nix
{ lib, pkgs, config, ... }:

let
  # Get all defined mail accounts from your central mail module
  allAccounts = config.hwc.home.core.mail.accounts or {};
  accVals = lib.attrValues allAccounts;

  # Helper function to generate a config block for a single account
  generateAccountBlock = acc: ''
    [${acc.name}]
    source   = maildir://~/Maildir/${acc.maildirName}
    from     = ${acc.realName} <${acc.address}>
    outgoing = msmtp
    copy-to  = ${if acc.type == "gmail" then "[Gmail]/Sent Mail" else "Sent"}
    # This tells aerc to run mbsync for this account
    sync-command = ${pkgs.isync}/bin/mbsync ${acc.name}-all
  '';

in
{
  files = {
    # Main aerc configuration file
    ".config/aerc/aerc.conf".text = ''
      # Main aerc configuration generated by Nix

      [ui]
      index-format = {{.Date | localdate | strftime "%Y-%m-%d"}} {{.From | name | trunc 25}} {{.Subject}}
      
      # Use msmtp for sending mail by default
      [compose]
      editor = ${pkgs.micro}/bin/micro

      [send]
      # Use the msmtp configuration that is already generated by the mail module
      send-command = ${pkgs.msmtp}/bin/msmtp -a default

      # Other settings can be added here
    '';

    # Account-specific configuration file
    ".config/aerc/accounts.conf".text =
      lib.concatStringsSep "\n\n" (map generateAccountBlock accVals);
  };
}
