# modules/home/apps/aerc/parts/config.nix
{ lib, pkgs, config, ... }:
let
  # Get all defined mail accounts from your central mail module
  allAccounts = config.hwc.home.core.mail.accounts or {};
  accVals = lib.attrValues allAccounts;
  # Helper function to generate a config block for a single account
  generateAccountBlock = acc: ''
    [${acc.name}]
    source   = maildir://~/Maildir/${acc.maildirName}
    from     = ${acc.realName} <${acc.address}>
    outgoing = msmtp
    copy-to  = ${if acc.type == "gmail" then "[Gmail]/Sent Mail" else "Sent"}
  '';

  # Main aerc config content
  aercConfContent = ''
    # Main aerc configuration generated by Nix
    [ui]
    index-format = {{.Date | localdate | strftime "%Y-%m-%d"}} {{.From | name | trunc 25}} {{.Subject}}
    
    [compose]
    editor = ${pkgs.micro}/bin/micro
    # Other settings can be added here
  '';

  # Accounts config content
  accountsConfContent = lib.concatStringsSep "\n\n" (map generateAccountBlock accVals);

  # Script to create aerc config files with correct permissions
  setupAercConfig = pkgs.writeShellScript "setup-aerc-config" ''
    mkdir -p "$HOME/.config/aerc"
    
    # Create aerc.conf with 600 permissions
    cat > "$HOME/.config/aerc/aerc.conf" << 'EOF'
${aercConfContent}
EOF
    chmod 600 "$HOME/.config/aerc/aerc.conf"
    
    # Create accounts.conf with 600 permissions
    cat > "$HOME/.config/aerc/accounts.conf" << 'EOF'
${accountsConfContent}
EOF
    chmod 600 "$HOME/.config/aerc/accounts.conf"
  '';
in
{
  # Use home.activation to create files with correct permissions
  home.activation.setupAercConfig = lib.hm.dag.entryAfter ["writeBoundary"] ''
    run ${setupAercConfig}
  '';
}
