# domains/mail/aerc/parts/sieve-filters.nix
#
# The Proton Sieve filters, generated from the mail taxonomy. Proton keeps
# only what must happen server-side, before mail reaches the phone or Laya:
#   01-junk     hard junk → Trash (taxonomy senders.trash, proton scope)
#   02-routing  the hide-my-email alias → its folder, plus recipient-address
#               labels (admin/office/datax/CTO) — interim, until the @-domain
#               labels of the Proton ⇄ Laya sync replace them
# Everything sender→topic (coaching, tech, ads, keepers) belongs to Laya
# routing rules, taught from aerc. No rule stars mail.
#
# Proton Sieve notes (proton.me/support/sieve-advanced-custom-filters):
#   fileinto a folder moves; fileinto a label adds it; missing targets are skipped.
#   Whether `stop` ends one filter or all is documented both ways; the split is
#   safe either way (at worst trashed junk also gets a recipient label).
{ lib }:
let
  t = (import ../../taxonomy/lib.nix { inherit lib; }).derived.protonTrash;

  q = s: ''"${lib.escape [ "\\" "\"" ] s}"'';
  list = xs: "[${lib.concatMapStringsSep ", " q xs}]";

  # A domain entry covers the domain and its subdomains.
  trashTests = lib.optionals (t.domains != []) [
      ''address :domain :is "from" ${list t.domains}''
      ''address :domain :matches "from" ${list (map (d: "*.${d}") t.domains)}''
    ]
    ++ lib.optional (t.addresses != []) ''address :all :is "from" ${list t.addresses}''
    ++ lib.optional (t.lists != []) ''header :is "x-pm-list-identifier" ${list t.lists}'';

  recipientLabels = [
    { test = ''address :all :is ["To", "Cc", "Bcc"] "admin@iheartwoodcraft.com"'';  label = "admin"; }
    { test = ''address :all :is ["To", "Cc", "Bcc"] "office@iheartwoodcraft.com"''; label = "office"; }
    { test = ''address :domain :is ["To", "Cc", "Bcc"] "contractorcto.com"'';       label = "datax"; }
    { test = ''address :all :is ["To", "Cc", "Bcc"] "eric@contractorcto.com"'';     label = "CTO"; }
  ];
  recipientRule = r: ''
    if ${r.test} {
        fileinto ${q r.label};
    }'';
  n = xs: toString (builtins.length xs);
  header = name: ''
    # Proton filter "${name}" — generated by nixos-hwc
    # domains/mail/aerc/parts/sieve-filters.nix. Do not edit in Proton; paste over it.
    require ["fileinto", "imap4flags"];
  '';
in
{
  # Changes whenever senders.trash changes. Must be ordered first in Proton.
  "01-junk.sieve" = ''
    ${header "01 - Junk"}
    # Hard junk → Trash (${n t.domains} domains, ${n t.addresses} addresses, ${n t.lists} newsletter lists)
    # Source of truth: domains/mail/taxonomy/data.nix (senders.trash).
    if anyof (
        ${lib.concatStringsSep ",\n        " trashTests}
    ) {
        addflag "\\Seen";
        fileinto "Trash";
        stop;
    }
  '';

  # Rarely changes; recipient labels retire when the @-domain sync labels land.
  "02-routing.sieve" = ''
    ${header "02 - Routing"}
    # Hide-my-email alias → folder
    if address :all :is ["To", "Cc", "Bcc"] "camelcity.derail128@passmail.com" {
        fileinto "hide_my_email";
        stop;
    }

    # Recipient labels (additive)
    ${lib.concatMapStringsSep "\n" recipientRule recipientLabels}
  '';
}
