# domains/mail/aerc/parts/sieve-filters.nix
#
# The Proton Sieve filters, generated from the mail taxonomy. Proton keeps
# only what must happen server-side, before mail reaches the phone or Laya:
#   01-junk     hard junk → Trash (taxonomy senders.trash, proton scope)
#   02-routing  preserves reviewed Seen and Archive actions and alias routing.
# Eric deleted the legacy labels; System One owns all @-label assignments.
# Interim routing retires in S4 when reviewed Laya rules preserve these actions.
# No rule stars mail.
#
# Proton Sieve notes (proton.me/support/sieve-advanced-custom-filters):
#   fileinto a folder moves; fileinto a label adds it; missing targets are skipped.
#   `stop` ends all subsequent filters; order 01-junk first.
{ lib }:
let
  t = (import ../../taxonomy/lib.nix { inherit lib; }).derived.protonTrash;

  q = s: ''"${lib.escape [ "\\" "\"" ] s}"'';
  list = xs: "[${lib.concatMapStringsSep ", " q xs}]";

  # A domain entry covers the domain and its subdomains.
  trashTests = lib.optionals (t.domains != []) [
      ''address :domain :is "from" ${list t.domains}''
      ''address :domain :matches "from" ${list (map (d: "*.${d}") t.domains)}''
    ]
    ++ lib.optional (t.addresses != []) ''address :all :is "from" ${list t.addresses}''
    ++ lib.optional (t.lists != []) ''header :is "x-pm-list-identifier" ${list t.lists}'';

  address = part: match: fields: values:
    ''address :${part} :${match} ${list fields} ${list values}'';
  from = values: address "all" "is" [ "From" ] values;
  to = values: address "all" "is" [ "To" "Cc" "Bcc" ] values;
  lists = values: ''header :is "x-pm-list-identifier" ${list values}'';
  any = tests: "anyof (${lib.concatStringsSep ", " tests})";
  all = tests: "allof (${lib.concatStringsSep ", " tests})";

  # Temporary by design: retire this data list in S4 after reviewed Laya
  # routing rules preserve these actions. Label-only rules were removed after
  # Eric deleted their targets on 2026-09-30; do not guess replacement Domains.
  routingRules = [
    { test = any [ (from [ "notifications@github.com" "noreply@status.io" ])
        ''header :contains "Subject" "Your Weekly WP Mail SMTP Summary for iheartwoodcraft.com"'' ];
      seen = true; }
    { test = lists [ "@noreply@mxtoolbox.com" "@no-reply@email.claude.com"
        "@noreply@business-updates.facebook.com" "@dist.admin1013@scorevolunteer.org" ];
      seen = true; spamGuard = false; }
    { test = from [ "no-reply@accounts.google.com" ]; seen = true; }
    { test = lists [ "@vimeo@vimeo.com" ]; archive = true; seen = true; spamGuard = false; }
    { test = from [ "thecodinggopher@substack.com" ]; archive = true; seen = true; }
    { test = any [ (address "all" "contains" [ "From" ] [ "builds@sr.ht" "aerc" ])
        (address "all" "contains" [ "To" "Cc" "Bcc" ]
          [ "~rjarry/aerc-devel@lists.sr.ht" "~rjarry/aerc-discuss@lists.sr.ht" ]) ];
      archive = true; seen = true; }
    { test = address "all" "contains" [ "From" ] [ "dmarc" ];
      archive = true; seen = true; }
    { test = all [ ''header :contains "Subject" "New demo request →"''
        (from [ "support@comms.datax.to" ]) (to [ "hello@contractorcto.com" ]) ];
      archive = true; seen = true; }
  ];
  spamTest = ''allof (environment :matches "vnd.proton.spam-threshold" "*", spamtest :value "ge" :comparator "i;ascii-numeric" "''${1}")'';
  routingRule = r: ''
    if ${if r.spamGuard or true then all [ "not ${spamTest}" r.test ] else r.test} {
        ${lib.optionalString (r.seen or false) ''addflag "\\Seen";''}
        ${lib.optionalString (r.archive or false) ''fileinto "Archive";''}
    }'';
  n = xs: toString (builtins.length xs);
  header = name: ''
    # Proton filter "${name}" — generated by nixos-hwc
    # domains/mail/aerc/parts/sieve-filters.nix. Do not edit in Proton; paste over it.
    require ["fileinto", "imap4flags"];
  '';
in
{
  # Changes whenever senders.trash changes. Must be ordered first in Proton.
  "01-junk.sieve" = ''
    ${header "01 - Junk"}
    # Hard junk → Trash (${n t.domains} domains, ${n t.addresses} addresses, ${n t.lists} newsletter lists)
    # Source of truth: domains/mail/taxonomy/data.nix (senders.trash).
    if anyof (
        ${lib.concatStringsSep ",\n        " trashTests}
    ) {
        addflag "\\Seen";
        fileinto "Trash";
        stop;
    }
  '';

  # Interim non-trash actions retire in S4. Sieve never assigns @ labels.
  "02-routing.sieve" = ''
    # Proton filter "02 - Routing" — generated by nixos-hwc
    # Reviewed Seen/Archive actions; removal condition: S4 ledger routing parity.
    # Legacy labels were deleted. System One owns all @-label assignments.
    require ["fileinto", "imap4flags", "environment", "variables", "relational", "comparator-i;ascii-numeric", "spamtest"];
    ${lib.concatMapStringsSep "\n" routingRule routingRules}

    # Hide-my-email alias → the one existing custom folder.
    if address :all :is ["To", "Cc", "Bcc"] "camelcity.derail128@passmail.com" {
        fileinto "hide_my_email";
        stop;
    }
  '';
}
