# domains/home/apps/codex/index.nix
{ config, lib, pkgs, inputs, ... }:
let
  cfg = config.hwc.home.apps.codex;
  codexPkg = if cfg.package != null then cfg.package else (pkgs.codex or null);
  home = config.home.homeDirectory;
  repo = cfg.sharedConfigRepo;

  # ~/.codex/AGENTS.md is DERIVED state: the Codex preamble, CLAUDE.md, and the
  # PRIMER-DIGEST block of engineering-principles.md, all from claude-config.
  # Rendered per host instead of committed, so two hosts can never conflict on
  # it and it cannot drift from its sources between renders. principles-lint.sh
  # checks the digest byte for byte. A hand-written file found in place is kept
  # once as AGENTS.md.pre-render.bak.
  agentsRender = pkgs.writeShellApplication {
    name = "codex-agents-render";
    runtimeInputs = with pkgs; [ coreutils gawk diffutils ];
    text = ''
      REPO=${lib.escapeShellArg repo}
      OUT="$HOME/.codex/AGENTS.md"
      MARK='<!-- GENERATED by codex-agents-render from the Nix-pinned agent harness -->'
      for src in codex/AGENTS.preamble.md CLAUDE.md standing-instructions.md engineering-principles.md; do
        [ -r "$REPO/$src" ] || { echo "codex-agents-render: missing $REPO/$src" >&2; exit 1; }
      done
      mkdir -p "$HOME/.codex"
      TMP=$(mktemp "$OUT.XXXXXX")
      {
        printf '%s\n\n' "$MARK"
        cat "$REPO/codex/AGENTS.preamble.md"
        cat "$REPO/CLAUDE.md"
        cat "$REPO/standing-instructions.md"
        printf '\n## Engineering principles digest\n\n<!-- BEGIN PRIMER-DIGEST -->\n'
        awk '/<!-- BEGIN PRIMER-DIGEST -->/{f=1;next} /<!-- END PRIMER-DIGEST -->/{f=0} f' \
          "$REPO/engineering-principles.md"
        printf '<!-- END PRIMER-DIGEST -->\n'
      } > "$TMP"
      if [ -e "$OUT" ] && ! head -n 1 "$OUT" | cmp -s - <(printf '%s\n' "$MARK") \
         && [ ! -e "$OUT.pre-render.bak" ]; then
        cp -p "$OUT" "$OUT.pre-render.bak"
        echo "codex-agents-render: kept hand-written $OUT as $OUT.pre-render.bak"
      fi
      if cmp -s "$TMP" "$OUT"; then rm -f "$TMP"; else mv "$TMP" "$OUT"; echo "codex-agents-render: wrote $OUT"; fi
    '';
  };

  # Codex runs a hook only after its hash is trusted in the host's config.toml.
  # The binary list mirrors the order T3's server PATH finds codex in; the hash
  # does not depend on the Codex version (measured 2026-09-17: a hook trusted by
  # the laptop's 0.146 matched the hash 0.154 computes).
  hooksTrust = pkgs.writeShellApplication {
    name = "codex-hooks-trust";
    # nodejs: the npm codex is a `#!/usr/bin/env node` launcher, and activation
    # PATH carries no node (measured on hwc-server: it fell through to 0.92).
    runtimeInputs = [ pkgs.python3 pkgs.nodejs ];
    text = ''
      exec python3 ${./hooks-trust.py} "$HOME/.npm-global/bin/codex" ${codexPkg}/bin/codex
    '';
  };
in
{
  #==========================================================================
  # OPTIONS
  #==========================================================================
  options.hwc.home.apps.codex = {
    enable = lib.mkEnableOption "OpenAI Codex CLI";

    package = lib.mkOption {
      type = lib.types.nullOr lib.types.package;
      default = null;
      description = "Codex package to use. If null, will use flake input.";
    };

    env = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {};
      description = "Additional environment variables for Codex CLI";
    };

    sharedConfigRepo = lib.mkOption {
      type = lib.types.str;
      default = toString inputs.agent-harness;
      description = "Nix-pinned agent harness source for Codex skills, hooks, and AGENTS.md inputs.";
    };

    sharedSkillSource = lib.mkOption {
      type = lib.types.str;
      default = "${repo}/skills";
      description = "Shared Agent Skills source tree used for selected Codex skill symlinks.";
    };

    sharedSkills = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "delegate"
        "dx2-evidence"
        "herdr"
        "project-closeout"
        "project-director"
      ];
      description = "Shared skills exposed to Codex from sharedSkillSource; the source files stay single-copy.";
    };

    # The engineering workflow skills live at ~/.agents/skills, the documented
    # Codex user-skill root. claude-config's codex-workflow-start.sh names that
    # path and principles-lint.sh checks all four there. It was hand-built on
    # hwc-laptop and absent on hwc-server (found 2026-09-17), so Codex threads
    # served from the server had no workflow skills at all.
    workflowSkills = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "stepwise-refinement"
        "chestertons-fence"
        "premortem"
        "datax-sr-triage"
      ];
      description = "Shared skills exposed at ~/.agents/skills (Codex user-skill root) from sharedSkillSource; the set principles-lint.sh verifies.";
    };

    # Hooks and instructions follow the claude-config share: a host that does
    # not carry the repo gets neither, instead of dangling links.
    shareHarness = lib.mkOption {
      type = lib.types.bool;
      default = config.hwc.home.apps.agent-harness.enable;
      description = "Link ~/.codex/hooks.json from sharedConfigRepo, render ~/.codex/AGENTS.md, and trust the shared hooks on activation and after each claude-config sync merge.";
    };
  };

  #==========================================================================
  # IMPLEMENTATION
  #==========================================================================
  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      home.packages = [ codexPkg ];

      home.sessionVariables = cfg.env;

      # Create config directory
      xdg.configFile."codex/.keep".text = "";

      # Claude already consumes the shared skill tree directly. Codex has its
      # own skill root, so expose only the cross-harness orchestration skills as
      # out-of-store symlinks instead of copying a second source tree.
      home.file = lib.listToAttrs (
        (map (skill:
          lib.nameValuePair ".codex/skills/${skill}" {
            source = config.lib.file.mkOutOfStoreSymlink "${cfg.sharedSkillSource}/${skill}";
          }
        ) cfg.sharedSkills)
        ++ (map (skill:
          lib.nameValuePair ".agents/skills/${skill}" {
            source = config.lib.file.mkOutOfStoreSymlink "${cfg.sharedSkillSource}/${skill}";
          }
        ) cfg.workflowSkills)
      );
    }

    (lib.mkIf cfg.shareHarness {
      home.packages = [ agentsRender hooksTrust ];

      # One hooks.json for every host. herdr's own entry is in it, so
      # `herdr integration install codex` must not be run against the link.
      home.file.".codex/hooks.json".source =
        config.lib.file.mkOutOfStoreSymlink "${repo}/codex/hooks.json";

      home.activation.codexSharedHarness = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
        run ${agentsRender}/bin/codex-agents-render \
          || echo "codex: AGENTS.md render failed" >&2
        run ${hooksTrust}/bin/codex-hooks-trust \
          || echo "codex: shared hooks are not all trusted — run codex-hooks-trust" >&2
      '';

    })

    #========================================================================
    # VALIDATION
    #========================================================================
    {
      assertions = [
        {
          assertion = codexPkg != null;
          message = "codex package must be available";
        }
      ];
    }
  ]);
}
