# Hardware configuration for hwc-laptop
# Generated by 'nixos-generate-config' and adapted for flake usage
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "thinkpad_acpi" ];
  boot.kernelParams = [ "thinkpad_acpi.fan_control=1" ];
  boot.extraModulePackages = [ ];
  
  fileSystems."/" =
      { device = "/dev/disk/by-uuid/0ebc1df3-65ec-4125-9e73-2f88f7137dc7";
        fsType = "ext4";
      };
  
    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/D278-E61F";
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };

  # Secondary SSD layout (planned):
  # - BACKUP (ext4, ~400G) mounted at /mnt/backup
  # - VMSTORE (ext4, ~300G) mounted at /mnt/vmstore
  # - Remaining space reserved for dual-boot OS installer
  #
  # Labels will be applied during partitioning/formatting; nofail avoids boot blocking if absent.
  fileSystems."/mnt/backup" = {
    device = "/dev/disk/by-uuid/e0d00e5d-7d65-4cef-b131-d2fac497a230";
    fsType = "ext4";
    options = [ "nofail" ];
  };

  # Optional VM store drive (often disconnected). Use a conditional mount so
  # rebuilds/boot don't hang when the device is absent.
  systemd.tmpfiles.rules = [
    "d /mnt/vmstore 0755 root root -"
  ];

  systemd.mounts = [
    {
      what = "/dev/disk/by-label/VMSTORE";
      where = "/mnt/vmstore";
      type = "ext4";
      options = "nofail,x-systemd.device-timeout=1s";
      # Removed wantedBy to prevent boot delays when device is absent
      # Mount will be available but not auto-started; can mount manually when device appears
      unitConfig.ConditionPathExists = "/dev/disk/by-label/VMSTORE";
    }
  ];

  # Encrypted swap file for hibernation support
  # Size: 16GB (recommended: 1.5x RAM for modern systems)
  swapDevices = [{
    device = "/var/swapfile";
    size = 16384; # 16GB in MB
    randomEncryption.enable = true; # Encrypt swap for security
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u2u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
