#!/usr/bin/env bash
# gen-index.sh — assemble a shared index from per-card fragments.
#
# Why: when many nightly-builds cards each contribute to one shared index file
# (e.g. docs/audits/README.md), every card after the first hits an add/add merge
# conflict. The fix (run-wrapper.md rule 8) is: each card drops a self-contained
# fragment at <dir>/index.d/<slug>.md and NEVER edits the shared file. This tool
# rebuilds the shared README's index section from those fragments, deterministically.
#
# Usage: gen-index.sh <dir>
#   Concatenates the sorted <dir>/index.d/*.md fragments into <dir>/README.md
#   between the markers below (creating them if absent). Idempotent.
set -euo pipefail

DIR="${1:?usage: gen-index.sh <dir>}"
README="$DIR/README.md"
FRAG_DIR="$DIR/index.d"
BEGIN="<!-- BEGIN index.d (generated by gen-index.sh — do not edit between markers) -->"
END="<!-- END index.d -->"

[ -d "$FRAG_DIR" ] || { echo "gen-index: no $FRAG_DIR — nothing to assemble"; exit 0; }

# Build the generated block from sorted fragments.
block="$(mktemp)"; trap 'rm -f "$block"' EXIT
{
  echo "$BEGIN"
  for f in $(printf '%s\n' "$FRAG_DIR"/*.md | sort); do
    [ -e "$f" ] || continue
    cat "$f"; echo
  done
  echo "$END"
} > "$block"

# Create README with markers if missing; else splice the block between markers.
if [ ! -f "$README" ]; then
  { echo "# $(basename "$DIR")"; echo; cat "$block"; } > "$README"
elif grep -qF "$BEGIN" "$README" && grep -qF "$END" "$README"; then
  awk -v b="$BEGIN" -v e="$END" -v blk="$block" '
    $0==b {while ((getline line < blk) > 0) print line; skip=1; next}
    $0==e {skip=0; next}
    !skip {print}
  ' "$README" > "$README.tmp" && mv "$README.tmp" "$README"
else
  { echo; cat "$block"; } >> "$README"
fi
echo "gen-index: assembled $(ls "$FRAG_DIR"/*.md 2>/dev/null | wc -l) fragment(s) into $README"
