title: HWC Server
theme: dark
color: zinc
headerStyle: clean
layout:
  HWC:
    style: row
    columns: 4
  DataX:
    style: row
    columns: 3
  Projects:
    style: row
    columns: 3
  Home:
    style: row
    columns: 3
  Media:
    style: row
    columns: 4
  Utilities:
    style: row
    columns: 4
